---
title: "Combined Marks"
output: html_document
params:
   Data: NA
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(numform)
library(psych)

```

```{r functions, include=FALSE}
# define formatting functions

# Report F(df1,df2)=xxx, p=.xxx
# frep<-function(f.obj){
#   s=paste0("F(", f.obj$Df[1],", ",f.obj$Df[2],")=",f_num(f.obj$`F value`[1],3),", ",f_pval(f.obj$`Pr(>F)`[1],alpha=.001,digits=3))
#   return(s)
# }
# 
# #make functions to nicely report N and percent two ways
# Npc<-function(num,tot){  # N (x%)
#   paste0(num," (",round(100*num/tot, digits=0),"%)")
# }
# 
# Npc2<-function(num,tot){ # (N, x%)
#   paste0("(",num,", ",round(100*num/tot, digits=0),"%)")
# }

# Function to add histograms to pairs plot
panel.hist <- function(x, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5))
    his <- hist(x, plot = FALSE)
    breaks <- his$breaks
    nB <- length(breaks)
    y <- his$counts
    y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = rgb(0, 1, 1, alpha = 0.5), ...)
    # lines(density(x), col = 2, lwd = 2) # Uncomment to add density lines
}

# Function to add correlation coefficients to pairs
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    Cor <- (cor(x, y, use="pairwise.complete.obs")) 
    txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
    if(missing(cex.cor)) {
        cex.cor <- 0.4 / strwidth(txt)
    }
    text(0.5, 0.5, txt,
         cex = 1 + cex.cor * Cor) # Resize the text by level of correlation
}
```

```{r process, include=FALSE}

Data<-params$Data




# Convert the grades to linear categories 0-15
# categorical=data.frame(c(17 , 25, 38, 42, 45, 48, 52, 55, 58, 62, 65, 68, 77, 88, 100),
#                        1:15, 
#                        c("Fail", "Fail", "Fail", "3rd", "3rd", "3rd", "2:II", "2:II", "2:II", "2:I", "2:I", "2:I", "1st", "1st", "1st"))
# colnames(categorical)<-c("Grade","category", "Class")

d<-Data %>% pivot_longer(-`Email address`, names_to = "Question", values_to = "Grade") %>% 
   mutate(
      Class=case_when(
      Grade == 0 ~ "Zero",
      Grade <40 ~ "Fail",
      Grade <50 ~ "3rd",
      Grade <60 ~ "2:II",
      Grade <70 ~ "2:I",
      Grade <101 ~ "1st",
      TRUE ~ "DN"
   ),
   Category=case_when(
      Grade == 0 ~ 0,
  
          Grade <=15 ~ 1,
          Grade <=25 ~ 2,
          Grade <=38 ~ 3,
      
 
          Grade <=42 ~4,
          Grade <=45 ~ 5,
          Grade <=48 ~ 6,
 
          Grade <=52 ~ 7,
          Grade <=55 ~ 8,
          Grade <=58 ~ 9,
 
          Grade <=62 ~ 10,
          Grade <=65 ~ 11,
          Grade <=68 ~ 12,
 
          Grade <=77 ~ 13,
          Grade <=88 ~ 14,
          Grade <=100 ~ 15,
      TRUE ~ 99
   )
   )

# exclude zeroes
nozeroes<-d %>% filter(Grade>0)



# build tables

# count N of each class per question
classTable<-d %>% 
   group_by(Question, Class) %>% 
   summarise(N=n()) 

# count total N for each question
classTableN<-d %>% 
   group_by(Question) %>% 
   summarise(Total=n())

# combine N and Total, convert to percentage and remove
classTable<-classTable %>% 
   left_join(.,classTableN) %>% 
   mutate(s=paste0(N," (",f_percent(100*N/Total),")")) %>% 
   select(-N, -Total) %>% 
   pivot_wider(names_from = Class, values_from = s)

# compute descriptives ignoring grades of zero
desc<-nozeroes %>% 
   group_by(Question) %>% 
   summarise(N=n(), M=f_num(mean(Grade, na.rm=T),2), SD=f_num(sd(Grade, na.rm=T),2))

# add descriptives to table
classTable<-left_join(classTable,desc)


# draw histogram of combined marks
# 

histbreaks=c(25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100)
   
final.hist<-nozeroes %>% 
   ggplot(aes(x=Grade))+
   geom_histogram(fill="white",colour="black", breaks=histbreaks)+
   scale_x_continuous(breaks=histbreaks)+
   theme_classic()
   



# make data for pairwise panel
pairs.data<-nozeroes %>% 
   select(`Email address`, Category, Question) %>% 
   pivot_wider(names_from = Question, values_from = Category) %>% 
   select(-`Email address`)




# now the markdown for the report ----

```

There were `r nrow(Data)` unique students with marks for this assessment. 

Questions obtaining marks above zero are summarised below.

`r knitr::kable(classTable, caption="Number of students at each class for each Question, and overall.")`

## Correlations between Questions and Overall mark
```{r plot_figs, echo=FALSE, message=FALSE, warning=FALSE}
# Creating the scatter plot matrix
#  if more than one answers per person
checknqs<-pairs.data %>% 
  mutate(rowid=row(.)) %>% 
  pivot_longer(-rowid) %>% 
  filter(!is.na(value)) %>% 
  group_by(rowid) %>% 
  summarise(nqs=n()) %>% 
  filter(nqs>2)   #  2 would be one question plus total

if(nrow(checknqs)>0){
pairs.panels(pairs.data,
             smooth = TRUE,      # If TRUE, draws loess smooths
             scale = FALSE,      # If TRUE, scales the correlation text font
             density = TRUE,     # If TRUE, adds density plots and histograms
             ellipses = TRUE,    # If TRUE, draws ellipses
             method = "pearson", # Correlation method (also "spearman" or "kendall")
             pch = 20,           # pch symbol
             lm = TRUE,         # If TRUE, plots linear fit rather than the LOESS (smoothed) fit
             cor = TRUE,         # If TRUE, reports correlations
             jiggle = TRUE,     # If TRUE, data points are jittered
             factor = 2,         # Jittering factor
             hist.col = 4,       # Histograms color
             stars = TRUE,       # If TRUE, adds significance level with stars
             ci = TRUE) 
}
```

## Distribution of final combined mark
```{r plot_hist, echo=FALSE, message=FALSE, warning=FALSE}
final.hist


```
