---
title: "Correlated Marks"
output: html_document
params:
   Data: NA
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(numform)


library(psych)

```

```{r functions, include=FALSE}
# define formatting functions



# Function to add histograms to pairs plot
panel.hist <- function(x, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5))
    his <- hist(x, plot = FALSE)
    breaks <- his$breaks
    nB <- length(breaks)
    y <- his$counts
    y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = rgb(0, 1, 1, alpha = 0.5), ...)
    # lines(density(x), col = 2, lwd = 2) # Uncomment to add density lines
}

# Function to add correlation coefficients to pairs
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    Cor <- (cor(x, y, use="pairwise.complete.obs")) 
    txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
    if(missing(cex.cor)) {
        cex.cor <- 0.4 / strwidth(txt)
    }
    text(0.5, 0.5, txt,
         cex = 1 + cex.cor * Cor) # Resize the text by level of correlation
}
```

```{r process, include=FALSE}

Data<-params$Data



# exclude zeroes
nozeroes<-Data %>% filter(Grade>0)





# make data for pairwise panel
pairs.data<-nozeroes %>% 
   select(`Email address`, Grade, file) %>% 
   pivot_wider(names_from = file, values_from = Grade) %>% 
   select(-`Email address`)




# now the markdown for the report ----

```

There were `r nrow(pairs.data)` unique students with marks for these assessments. 



## Correlations between Questions and Overall mark
```{r plot_figs, echo=FALSE, message=FALSE, warning=FALSE}
# Creating the scatter plot matrix
# 
pairs.panels(pairs.data,
             smooth = TRUE,      # If TRUE, draws loess smooths
             scale = FALSE,      # If TRUE, scales the correlation text font
             density = TRUE,     # If TRUE, adds density plots and histograms
             ellipses = TRUE,    # If TRUE, draws ellipses
             method = "pearson", # Correlation method (also "spearman" or "kendall")
             pch = 20,           # pch symbol
             lm = TRUE,         # If TRUE, plots linear fit rather than the LOESS (smoothed) fit
             cor = TRUE,         # If TRUE, reports correlations
             jiggle = TRUE,     # If TRUE, data points are jittered
             factor = 2,         # Jittering factor
             hist.col = 4,       # Histograms color
             stars = TRUE,       # If TRUE, adds significance level with stars
             ci = TRUE)    
```


